doctrine:
    dbal:
        url: '%env(resolve:DATABASE_PRODUCT)%://%env(resolve:DATABASE_USER)%:%env(resolve:DATABASE_PASSWORD)%@%env(resolve:DATABASE_HOST)%:%env(resolve:DATABASE_PORT)%/%env(resolve:DATABASE_DB)%?serverVersion=%env(resolve:DATABASE_SERVERVERSION)%'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:

            App\VideoBasedMarketing\Account\Domain\Entity:
                is_bundle: false
                dir: '%kernel.project_dir%/src/VideoBasedMarketing/Account/Domain/Entity'
                prefix: 'App\VideoBasedMarketing\Account\Domain\Entity'

            App\VideoBasedMarketing\Account\Infrastructure\Entity:
                is_bundle: false
                dir: '%kernel.project_dir%/src/VideoBasedMarketing/Account/Infrastructure/Entity'
                prefix: 'App\VideoBasedMarketing\Account\Infrastructure\Entity'


            App\VideoBasedMarketing\Membership\Domain\Entity:
                is_bundle: false
                dir: '%kernel.project_dir%/src/VideoBasedMarketing/Membership/Domain/Entity'
                prefix: 'App\VideoBasedMarketing\Membership\Domain\Entity'


            App\VideoBasedMarketing\Presentationpages\Domain\Entity:
                is_bundle: false
                dir: '%kernel.project_dir%/src/VideoBasedMarketing/Presentationpages/Domain/Entity'
                prefix: 'App\VideoBasedMarketing\Presentationpages\Domain\Entity'


            App\VideoBasedMarketing\Recordings\Domain\Entity:
                is_bundle: false
                dir: '%kernel.project_dir%/src/VideoBasedMarketing/Recordings/Domain/Entity'
                prefix: 'App\VideoBasedMarketing\Recordings\Domain\Entity'

            App\VideoBasedMarketing\Recordings\Infrastructure\Entity:
                is_bundle: false
                dir: '%kernel.project_dir%/src/VideoBasedMarketing/Recordings/Infrastructure/Entity'
                prefix: 'App\VideoBasedMarketing\Recordings\Infrastructure\Entity'

            App\VideoBasedMarketing\Recordings\Api\Recorder\V1\Entity:
                is_bundle: false
                dir: '%kernel.project_dir%/src/VideoBasedMarketing/Recordings/Api/Recorder/V1/Entity'
                prefix: 'App\VideoBasedMarketing\Recordings\Api\Recorder\V1\Entity'

            App\VideoBasedMarketing\RecordingRequests\Domain\Entity:
                is_bundle: false
                dir: '%kernel.project_dir%/src/VideoBasedMarketing/RecordingRequests/Domain/Entity'
                prefix: 'App\VideoBasedMarketing\RecordingRequests\Domain\Entity'

            App\VideoBasedMarketing\Mailings\Domain\Entity:
                is_bundle: false
                dir: '%kernel.project_dir%/src/VideoBasedMarketing/Mailings/Domain/Entity'
                prefix: 'App\VideoBasedMarketing\Mailings\Domain\Entity'

            App\VideoBasedMarketing\Settings\Domain\Entity:
                is_bundle: false
                dir: '%kernel.project_dir%/src/VideoBasedMarketing/Settings/Domain/Entity'
                prefix: 'App\VideoBasedMarketing\Settings\Domain\Entity'

            App\VideoBasedMarketing\Settings\Infrastructure\Entity:
                is_bundle: false
                dir: '%kernel.project_dir%/src/VideoBasedMarketing/Settings/Infrastructure/Entity'
                prefix: 'App\VideoBasedMarketing\Settings\Infrastructure\Entity'

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
