# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    router:
        default_uri: '%env(ROUTER_REQUEST_CONTEXT_SCHEME)%://%env(ROUTER_REQUEST_CONTEXT_HOST)%/%env(ROUTER_REQUEST_CONTEXT_BASE_URL)%'

    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: true
        cookie_samesite: 'none'
        storage_factory_id: session.storage.factory.native
        gc_probability: null # See https://symfony.com/doc/6.2/components/http_foundation/session_configuration.html#configuring-garbage-collection

    #esi: true
    #fragments: true
    php_errors:
        log: true

    set_locale_from_accept_language: true
    set_content_language_from_locale: true
    enabled_locales:
        - !php/enum App\Shared\Domain\Enum\Iso639_1Code::En->value
        - !php/enum App\Shared\Domain\Enum\Iso639_1Code::De->value
    default_locale: !php/enum App\Shared\Domain\Enum\Iso639_1Code::En->value

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
        http_client:
            mock_response_factory: App\Tests\Mocks\MockHttpClientCallback
