framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            sync: 'sync://'
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'

        routing:
            App\Shared\Infrastructure\SymfonyMessage\SyncSymfonyMessageInterface: sync
            App\Shared\Infrastructure\SymfonyMessage\AsyncSymfonyMessageInterface: async

        buses:
            messenger.bus.default:
                middleware:
                    - 'App\Shared\Infrastructure\SymfonyMessage\EventLoggerMiddleware'

when@test:
    framework:
        messenger:
            transports:
                async:
                    dsn: 'in-memory://'
                    options:
                        serialize: true
