nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: [ ]
        allow_headers: [ ]
        allow_methods: [ ]
        expose_headers: [ ]
        max_age: 0
        hosts: [ ]
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/api/':
            origin_regex: true
            allow_origin: [ '%env(CORS_ALLOW_ORIGIN)%' ]
            allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE' ]
            allow_credentials: true
            allow_headers: [ 'Content-Type', 'Authorization', 'Set-Cookie' ]
            expose_headers: [ 'Link', 'Cookie' ]
            max_age: 3600
        '^/': null
