framework:
    default_locale: !php/enum App\Shared\Domain\Enum\Iso639_1Code::En->value
    translator:
        default_path: '%kernel.project_dir%/translations'
        paths:
            - '%kernel.project_dir%/src/Shared/Presentation/Resources/translations'
            - '%kernel.project_dir%/src/VideoBasedMarketing/Account/Presentation/Resources/translations'
            - '%kernel.project_dir%/src/VideoBasedMarketing/Organization/Presentation/Resources/translations'
            - '%kernel.project_dir%/src/VideoBasedMarketing/Dashboard/Presentation/Resources/translations'
            - '%kernel.project_dir%/src/VideoBasedMarketing/Membership/Presentation/Resources/translations'
            - '%kernel.project_dir%/src/VideoBasedMarketing/Recordings/Presentation/Resources/translations'
            - '%kernel.project_dir%/src/VideoBasedMarketing/RecordingRequests/Presentation/Resources/translations'
            - '%kernel.project_dir%/src/VideoBasedMarketing/Presentationpages/Presentation/Resources/translations'
            - '%kernel.project_dir%/src/VideoBasedMarketing/Mailings/Presentation/Resources/translations'
            - '%kernel.project_dir%/src/VideoBasedMarketing/Settings/Presentation/Resources/translations'
            - '%kernel.project_dir%/src/VideoBasedMarketing/AudioTranscription/Presentation/Resources/translations'
        fallbacks:
            - !php/enum App\Shared\Domain\Enum\Iso639_1Code::En->value
            - !php/enum App\Shared\Domain\Enum\Iso639_1Code::De->value
