twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        CookiesService: '@App\Service\Aspect\Cookies\CookiesService'
        ContentDeliveryService: '@App\Service\Aspect\ContentDelivery\ContentDeliveryService'
        MembershipService: '@App\Service\Feature\Membership\MembershipService'
        VideoService: '@App\Service\Feature\Recordings\VideoService'
        ShortIdService: '@App\Service\Aspect\ShortId\ShortIdService'

when@test:
    twig:
        strict_variables: true
