twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        ContentDeliveryService: '@App\Service\Aspect\ContentDelivery\ContentDeliveryService'

when@test:
    twig:
        strict_variables: true
