twig:
    default_path: '%kernel.project_dir%/templates'

    paths:
        'src/VideoBasedMarketing/Account/Presentation/Resources/templates': 'videobasedmarketing.account'
        'src/VideoBasedMarketing/Membership/Presentation/Resources/templates': 'videobasedmarketing.membership'

    globals:
        TwigHelperService: '@App\Shared\Twig\Presentation\Service\TwigHelperService'

when@test:
    twig:
        strict_variables: true
