twig:
    default_path: '%kernel.project_dir%/templates'

    paths:
        '%kernel.project_dir%/public/generated-content/': 'generated_content'

        'src/Shared/Presentation/Resources/templates': 'shared'

        'src/VideoBasedMarketing/Account/Presentation/Resources/templates':            'videobasedmarketing.account'
        'src/VideoBasedMarketing/Organization/Presentation/Resources/templates':       'videobasedmarketing.organization'
        'src/VideoBasedMarketing/Membership/Presentation/Resources/templates':         'videobasedmarketing.membership'
        'src/VideoBasedMarketing/Dashboard/Presentation/Resources/templates':          'videobasedmarketing.dashboard'
        'src/VideoBasedMarketing/Presentationpages/Presentation/Resources/templates':  'videobasedmarketing.presentationpages'
        'src/VideoBasedMarketing/Recordings/Presentation/Resources/templates':         'videobasedmarketing.recordings'
        'src/VideoBasedMarketing/RecordingRequests/Presentation/Resources/templates':  'videobasedmarketing.recording_requests'
        'src/VideoBasedMarketing/Mailings/Presentation/Resources/templates':           'videobasedmarketing.mailings'
        'src/VideoBasedMarketing/Settings/Presentation/Resources/templates':           'videobasedmarketing.settings'
        'src/VideoBasedMarketing/AudioTranscription/Presentation/Resources/templates': 'videobasedmarketing.audio_transcription'
        'src/VideoBasedMarketing/VideoEditor/Presentation/Resources/templates':        'videobasedmarketing.video_editor'

    globals:
        TwigHelperService: '@App\Shared\Presentation\Service\TwigHelperService'

when@test:
    twig:
        strict_variables: true
