api.extension.v1.get_session_info:
  path: /extension/v1/session-info
  controller: App\VideoBasedMarketing\Recordings\Api\Extension\V1\Controller\ExtensionApiV1Controller::getSessionInfoAction
  methods: [ GET ]

api.extension.v1.create_recording_session:
  path: /extension/v1/recording-sessions/
  controller: App\VideoBasedMarketing\Recordings\Api\Extension\V1\Controller\ExtensionApiV1Controller::createRecordingSessionAction
  methods: [ POST ]

api.extension.v1.recording_session.handle_video_chunk:
  path: /extension/v1/recording-sessions/{recordingSessionId}/video-chunks/
  controller: App\VideoBasedMarketing\Recordings\Api\Extension\V1\Controller\ExtensionApiV1Controller::handleRecordingSessionVideoChunkAction
  methods: [ POST ]
