feature.recordings.recording_session.video_chunk.asset:
  path: /generated-content/recording-sessions/{recordingSessionId}/video-chunks/{chunkId}

feature.recordings.recording_session.full_video.asset:
  path: /generated-content/recording-sessions/{recordingSessionId}/full-video.{extension}

feature.recordings.recording_session.full_video.preview.asset:
  path: /generated-content/recording-sessions/{recordingSessionId}/full-video-preview.{extension}

feature.recordings.recording_session.full_video.poster.asset:
  path: /generated-content/recording-sessions/{recordingSessionId}/full-video-poster.{extension}
