feature.recordings.recording_session.video_chunk.asset:
  path: /generated-content/recording-sessions/{recordingSessionId}/video-chunks/{chunkId}

feature.recordings.recording_session.recording_preview.asset-redirect:
  path: /my/recordings/recording-sessions/{recordingSessionId}/recording-preview-asset-redirect
  controller: App\VideoBasedMarketing\Recordings\Presentation\Controller\RecordingsController::recordingPreviewAssetRedirectAction
  methods: [ GET ]

feature.recordings.recording_session.recording_preview.asset:
  path: /generated-content/recording-sessions/{recordingSessionId}/recording-preview-video.{extension}

feature.recordings.recording_session.recording_preview.poster.asset:
  path: /generated-content/recording-sessions/{recordingSessionId}/recording-preview-video-poster.{extension}


feature.recordings.video.missing_poster_asset_placeholder:
  path: /assets/images/feature/recordings/video/missing_poster_asset_placeholder.gif

feature.recordings.video.missing_full_asset_placeholder:
  path: /assets/images/feature/recordings/video/missing_full_asset_placeholder.mp4


feature.recordings.video.poster_still.asset:
  path: /generated-content/video-assets/{videoId}/poster-still.{extension}

feature.recordings.video.poster_animated.asset:
  path: /generated-content/video-assets/{videoId}/poster-animated.{extension}

feature.recordings.video.full.asset:
  path: /generated-content/video-assets/{videoId}/full.{extension}


# TODO: change path in recorder, see https://trello.com/c/9XbHtrku/32-recorder-nutzt-hardcoded-settings-url-muss-dynamisch-per-info-vom-backend-kommen
legacy.feature.recordings.recording_settings.get:
  path: /settings/
  methods: [ GET ]
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: api.feature.recordings.recording_settings_bag.get
    permanent: false
    keepQueryParams: true

legacy.feature.recordings.recording_settings.set:
  path: /settings/
  methods: [ POST ]
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: api.feature.recordings.recording_settings_bag.set
    permanent: false
    keepQueryParams: true
    keepRequestMethod: true


feature.recordings.video.share_link:
  path: /v/{videoShortId}
  controller: App\VideoBasedMarketing\Recordings\Presentation\Controller\VideosController::videoShareLinkAction
  methods: [ GET ]
