features:
    resource: 'routes/feature/*.yaml'
    prefix: /{_locale}
    requirements:
        _locale: en|de
    defaults:
        _locale: en

aspects:
    resource: 'routes/aspect/*.yaml'

api:
    resource: 'routes/api/**/*.yaml'
    prefix: /api

catchall:
    path:     /{catchall}
    controller: App\Controller\CatchallController::indexAction
    methods:  [GET]
    requirements:
        catchall: ".+"

root:
    path:     /
    controller: App\Controller\CatchallController::indexAction
    methods:  [GET]
