account:
    resource: '../src/VideoBasedMarketing/Account/Infrastructure/Resources/config/routes.yaml'

localized:
    resource: 'routes/localized/**/*.yaml'
    prefix: /{_locale}
    requirements:
        _locale: en|de
    defaults:
        _locale: en

non_localized:
    resource: 'routes/non_localized/**/*.yaml'

api:
    resource: 'routes/api/**/*.yaml'
    prefix: /api

tailwind_playground:
    path: /tailwind-playground
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: /tailwind_playground.html.twig

catchall:
    path:     /{catchall}
    controller: App\Shared\Presentation\Controller\CatchallController::indexAction
    methods:  [GET]
    requirements:
        catchall: ".+"

root:
    path:     /
    controller: App\Shared\Presentation\Controller\CatchallController::indexAction
    methods:  [GET]
