shared.infrastructure:
    resource: '../src/Shared/Infrastructure/Resources/config/routes.yaml'


videobasedmarketing.account.infrastructure:
    resource: '../src/VideoBasedMarketing/Account/Infrastructure/Resources/config/routes.yaml'


videobasedmarketing.presentationpages.infrastructure:
    resource: '../src/VideoBasedMarketing/Presentationpages/Infrastructure/Resources/config/routes.yaml'


videobasedmarketing.recordings.presentation:
    resource: '../src/VideoBasedMarketing/Recordings/Presentation/Resources/config/routes.yaml'

videobasedmarketing.recordings.api.recorder.v1:
    resource: '../src/VideoBasedMarketing/Recordings/Api/Recorder/V1/Resources/config/routes.yaml'


videobasedmarketing.settings.presentation:
    resource: '../src/VideoBasedMarketing/Settings/Presentation/Resources/config/routes.yaml'


# This needs to be last because it contains the catchall route definitions.
shared.presentation:
    resource: '../src/Shared/Presentation/Resources/config/routes.yaml'
