shared:
    resource: '../src/Shared/Presentation/Resources/config/routes.yaml'

videobasedmarketing.account:
    resource: '../src/VideoBasedMarketing/Account/Infrastructure/Resources/config/routes.yaml'

videobasedmarketing.presentationpages:
    resource: '../src/VideoBasedMarketing/Presentationpages/Infrastructure/Resources/config/routes.yaml'


non_localized:
    resource: 'routes/non_localized/**/*.yaml'

catchall.pattern:
    path:     /{catchall}
    controller: App\Shared\Presentation\Controller\CatchallController::indexAction
    methods:  [GET]
    requirements:
        catchall: ".+"

catchall.root:
    path:     /
    controller: App\Shared\Presentation\Controller\CatchallController::indexAction
    methods:  [GET]
