shared.infrastructure:
    resource: '../src/Shared/Infrastructure/Resources/config/routes.yaml'

videobasedmarketing.account.infrastructure:
    resource: '../src/VideoBasedMarketing/Account/Infrastructure/Resources/config/routes.yaml'

videobasedmarketing.presentationpages.infrastructure:
    resource: '../src/VideoBasedMarketing/Presentationpages/Infrastructure/Resources/config/routes.yaml'


non_localized:
    resource: 'routes/non_localized/**/*.yaml'


# This needs to be last because it contains the catchall route definitions.
shared.presentation:
    resource: '../src/Shared/Presentation/Resources/config/routes.yaml'
