localized:
    resource: 'routes/localized/**/*.yaml'
    prefix: /{_locale}
    requirements:
        _locale: en|de
    defaults:
        _locale: en

non_localized:
    resource: 'routes/non_localized/**/*.yaml'

api:
    resource: 'routes/api/**/*.yaml'
    prefix: /api

catchall:
    path:     /{catchall}
    controller: App\Controller\CatchallController::indexAction
    methods:  [GET]
    requirements:
        catchall: ".+"

root:
    path:     /
    controller: App\Controller\CatchallController::indexAction
    methods:  [GET]
