services:
    App\Tests\:
        resource: '../tests/'
        exclude:
            - '../tests/bootstrap.php'
            - '../tests/**/Resources/**/*'

    'knpu.oauth2.client.linkedin':
        class: 'KnpU\OAuth2ClientBundle\Client\Provider\LinkedInClient'
        factory: [
            'App\Tests\Mocks\KnpUOAuth2ClientBundleLinkedInClientFactory',
            'createMock'
        ]
        public: true
