# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.timezone: '%env(APP_TIMEZONE)%'

    app.routing.locale_requirement: 'en|de'

    app.routing.route_prefix.api: 'api'

    app.routing.route_prefix.without_locale.protected: 'my'

    app.routing.route_prefix.with_locale.unprotected.en: '{_locale}'
    app.routing.route_prefix.with_locale.unprotected.de: '{_locale}'

    app.routing.route_prefix.with_locale.protected.en: '{_locale}/my'
    app.routing.route_prefix.with_locale.protected.de: '{_locale}/mein-bereich'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/**/Enum/*'
            - '../src/**/Resources/**/*'
            - '../src/Kernel.php'
            # We do not exclude '../src/**/Entity/*', because since Symfony 6.2, this results in error 'The definition ".service_locator.SAH4WVS" has a reference to an abstract definition "App\VideoBasedMarketing\Presentationpages\Domain\Entity\Presentationpage". Abstract definitions cannot be the target of references.'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
