api.feature.recordings.recording_session.get_info:
  path: /feature/recordings/recording-sessions/{recordingSessionId}/info
  controller: App\VideoBasedMarketing\Recordings\Api\Controller\RecordingsApiController::getRecordingSessionInfoAction
  methods: [ GET ]


api.feature.recordings.recording_settings_bag.get:
  path: /feature/recordings/recording-settings-bag
  controller: App\VideoBasedMarketing\Recordings\Api\Controller\RecordingsApiController::getRecordingSettingsBagAction
  methods: [ GET ]

api.feature.recordings.recording_settings_bag.set:
  path: /feature/recordings/recording-settings-bag
  controller: App\VideoBasedMarketing\Recordings\Api\Controller\RecordingsApiController::setRecordingSettingsBagAction
  methods: [ POST ]


api.feature.recordings.recording_session.handle_video_chunk:
  path: /feature/recordings/recording-sessions/{recordingSessionId}/video-chunks/
  controller: App\VideoBasedMarketing\Recordings\Api\Controller\RecordingsApiController::handleRecordingSessionVideoChunkAction
  methods: [ POST ]
