feature.landingpages.homepage:
  path: /
  controller: App\VideoBasedMarketing\Landingpages\Presentation\Controller\LandingpagesController::homepageAction
  methods: [ GET ]

feature.landingpages.features:
  path: /features
  controller: App\VideoBasedMarketing\Landingpages\Presentation\Controller\LandingpagesController::featuresAction
  methods: [ GET ]

feature.landingpages.pricing:
  path: /pricing
  controller: App\VideoBasedMarketing\Landingpages\Presentation\Controller\LandingpagesController::pricingAction
  methods: [ GET ]
