feature.landingpages.homepage:
  path: /
  controller: App\Shared\Presentation\Controller\ContentpagesController::homepageAction
  methods: [ GET ]

feature.landingpages.features:
  path: /features
  controller: App\Shared\Presentation\Controller\ContentpagesController::featuresAction
  methods: [ GET ]

feature.landingpages.pricing:
  path: /pricing
  controller: App\Shared\Presentation\Controller\ContentpagesController::pricingAction
  methods: [ GET ]
