feature.presentationpage_templates.overview:
  path: /my/presentationpage-templates/
  controller: App\Controller\Feature\PresentationpageTemplates\PresentationpageTemplatesController::overviewAction
  methods: [ GET ]

feature.presentationpage_templates.add_form:
  path: /my/presentationpage-templates/add
  controller: App\Controller\Feature\PresentationpageTemplates\PresentationpageTemplatesController::addFormAction
  methods: [ GET, POST ]

feature.presentationpage_templates.preview:
  path: /my/presentationpage-templates/{templateId}/preview
  controller: App\Controller\Feature\PresentationpageTemplates\PresentationpageTemplatesController::previewAction
  methods: [ GET ]
