feature.presentationpage_templates.overview:
  path: /my/presentationpage-templates/
  controller: App\Controller\Feature\PresentationpageTemplates\PresentationpageTemplatesController::overviewAction
  methods: [ GET ]

feature.presentationpages.create_from_video:
  path: /my/presentationpage-templates/create
  controller: App\Controller\Feature\PresentationpageTemplates\PresentationpageTemplatesController::createAction
  methods: [ POST ]

feature.presentationpage_templates.editor:
  path: /my/presentationpage-templates/{presentationpageTemplateId}/editor
  controller: App\Controller\Feature\PresentationpageTemplates\PresentationpageTemplatesController::editorAction
  methods: [ GET, POST ]

feature.presentationpage_templates.preview:
  path: /my/presentationpage-templates/{templateId}/preview
  controller: App\Controller\Feature\PresentationpageTemplates\PresentationpageTemplatesController::previewAction
  methods: [ GET ]
