feature.presentationpages.overview:
  path: /my/presentationpages/
  controller: App\Controller\Feature\Presentationpages\PresentationpagesController::overviewAction
  methods: [ GET ]

feature.presentationpages.create_template:
  path: /my/presentationpages/template/
  controller: App\Controller\Feature\Presentationpages\PresentationpagesController::createTemplateAction
  methods: [ POST ]

feature.presentationpages.create_from_video:
  path: /my/presentationpages/from-video/{videoId}
  controller: App\Controller\Feature\Presentationpages\PresentationpagesController::createFromVideoAction
  methods: [ POST ]

feature.presentationpages.editor:
  path: /my/presentationpages/{presentationpageId}/editor
  controller: App\Controller\Feature\Presentationpages\PresentationpagesController::editorAction
  methods: [ GET, POST ]

feature.presentationpages.preview:
  path: /my/presentationpages/{presentationpageId}/preview
  controller: App\Controller\Feature\Presentationpages\PresentationpagesController::previewAction
  methods: [ GET ]
