feature.recordings.recording_studio:
  path: /my/recordings/recording-studio
  controller: App\Controller\Feature\Recordings\RecordingsController::recordingStudioAction
  methods: [ GET ]

feature.recordings.return_from_recording_studio:
  path: /my/recordings/return-from-recording-session
  controller: App\Controller\Feature\Recordings\RecordingsController::returnFromRecordingStudioAction
  methods: [ GET ]

feature.recordings.videos.overview:
  path: /my/recordings/videos/
  controller: App\Controller\Feature\Recordings\VideosController::videosOverviewAction
  methods: [ GET ]

feature.recordings.video.show_with_video_only_presentationpage_template:
  path: /video/{videoId}/wvopt
  controller: App\Controller\Feature\Recordings\VideosController::showWithVideoOnlyPresentationpageTemplateAction
  methods: [ GET ]
