feature.recordings.recording-studio:
  path: /my/recordings/recording-studio
  controller: App\Controller\Feature\Recordings\RecordingsController::recordingStudioAction
  methods: [ GET ]

feature.recordings.return_from_recording_session:
  path: /my/recordings/return-from-recording-session
  controller: App\Controller\Feature\Recordings\RecordingsController::returnFromRecordingSessionAction
  methods: [ GET ]

feature.recordings.recording_sessions.overview:
  path: /my/recordings/recording-sessions/
  controller: App\Controller\Feature\Recordings\RecordingsController::recordingSessionsOverviewAction
  methods: [ GET ]

feature.recordings.recording_session.full_video_blob.get:
  path: /my/recordings/recording-sessions/{recordingSessionId}/full-video-blob.webm
  controller: App\Controller\Feature\Recordings\RecordingsController::getRecordingSessionFullVideoBlobAction
  methods: [ GET ]

feature.recordings.recording_session.full_video_preview_image.get:
  path: /my/recordings/recording-sessions/{recordingSessionId}/full-video-preview-image.gif
  controller: App\Controller\Feature\Recordings\RecordingsController::getRecordingSessionFullVideoPreviewImageAction
  methods: [ GET ]
